### PR TITLE
feature: versioned interrupt signal

### PR DESCRIPTION
**Pull request by grkek**

### CODE REVIEW

**Comment by grkek** [comment]
@yanecc What do you think of this feature, I think it is enough to have a versioned interrupt handler?

**Comment by yanecc** [comment]
`Process.on_interrupt` is available since crystal 1.8.0.

**Comment by yanecc** [comment]
And you may like
```
{% if compare_versions(Crystal::VERSION, "1.12.0") >= 0 %}
  ...
{% elsif compare_versions(Crystal::VERSION, "1.8.0") < 0 %}
  ...
{% else %}
  ...
{% end %}
```

**Comment by grkek** [comment]
> `Crystal::VERSION.split(".").map(&.to_i)` will cause unhandled exception when building with crystal versions under development such as `1.13.0-dev` and you may like:
> 
> ```
> {% if compare_versions(Crystal::VERSION, "1.12.0") >= 0 %}
>   ...
> {% elsif compare_versions(Crystal::VERSION, "1.8.0") < 0 %}
>   ...
> {% else %}
>   ...
> {% end %}
> ```

You are right, I will add a check to remove such cases from the starting string.

**Comment by yanecc** [comment]
> `Process.on_interrupt` is available since crystal 1.8.0.

@grkek

**Pull request merged**
