### PR TITLE
Support setting routes for serving static files

### PR DESCRIPTION
**Pull request by yanecc**
This is a work in progress, aiming to address #60
There is still much work to do ...

### CODE REVIEW

**Comment by yanecc** [comment]
It can work as expected now but with unhandled errors.

```
ERROR - http.server: Unhandled exception on HTTP::Handler
Closed stream (IO::Error)
  from A:\Scoop\apps\crystal\current\src\http\server\response.cr:204 in 'check_headers'
  from A:\Scoop\apps\crystal\current\src\http\server\response.cr:40 in 'status='
  from A:\Scoop\apps\crystal\current\src\http\server\response.cr:89 in 'status_code='
  from C:\Users\Sunrise\Documents\CodeRepo\Crystal\test\static-server\lib\grip\src\grip\handlers\exception.cr:16 in 'call'
  from A:\Scoop\apps\crystal\current\src\http\server\request_processor.cr:51 in 'process'
  from A:\Scoop\apps\crystal\current\src\http\server.cr:521 in 'handle_client'
  from A:\Scoop\apps\crystal\current\src\http\server.cr:451 in '->'
  from A:\Scoop\apps\crystal\current\src\fiber.cr:141 in 'run'
  from A:\Scoop\apps\crystal\current\src\fiber.cr:93 in '->'
```

**Comment by grkek** [comment]
> Closed stream (IO::Error)

Can you investigate why does this happen?

**Comment by yanecc** [comment]
Relevant issue: https://github.com/crystal-lang/crystal/issues/14566

**Comment by grkek** [comment]
> Relevant issue: [crystal-lang/crystal#14566](https://github.com/crystal-lang/crystal/issues/14566)

Should be fixed by #66

**Comment by yanecc** [comment]
The code works well now and is reviewable.

**Comment by grkek** [comment]
@yanecc Can you provide an example?

**Comment by grkek** [comment]
> The code works well now and is reviewable.

I am going to modify this code a little bit to be a bit more Grip-esque, I will update the documentation with the news.

**Comment by yanecc** [comment]
> @yanecc Can you provide an example?

Sure, here is a simple illustration.

``` crystal
class Application < Grip::Application
  def initialize()
    super(environment: "development", serve_static: true)
  end

  getter host : String = "127.0.0.1"
  # getter pubilc_dir : String = "./public"
  getter static_routes : Hash(String, String) = {
    "/foo/bar" => "./dir1",
    "/test"    => "./path/to/dir2",
  }
end

# By default, when serve_static is set to true, public_dir will be set to "./public".
# You could use pubilc_dir to set the static directory.

# If static_routes is set, pubilc_dir will be overwritten.
# GET http://127.0.0.1          #=> 404 Not Found
# GET http://127.0.0.1/foo/bar  #=> 200 OK -> ./dir1/index.html
# GET http://127.0.0.1/test     #=> 200 OK -> ./path/to/dir2/index.html
```

**Comment by grkek** [comment]
> > @yanecc Can you provide an example?
> 
> Sure, here is a simple illustration.
> 
> ```crystal
> class Application < Grip::Application
>   def initialize()
>     super(environment: "development", serve_static: true)
>   end
> 
>   getter host : String = "127.0.0.1"
>   # getter pubilc_dir : String = "./public"
>   getter static_routes : Hash(String, String) = {
>     # "/"        => "./public",
>     "/foo/bar" => "./dir1",
>     "/baz"     => "./path/to/dir2",
>   }
> end
> 
> # By default, when serve_static is set to true, public_dir will be set to "./public".
> # You could use pubilc_dir to set the static directory.
> 
> # If static_routes is set, pubilc_dir will be overwritten.
> # GET http://127.0.0.1          #=> 404 Not Found
> # GET http://127.0.0.1/foo/bar  #=> 200 OK -> ./dir1/index.html
> # GET http://127.0.0.1/baz      #=> 200 OK -> ./path/to/dir2/index.html
> ```

I updated the version of Grip to 3.0.0 since I implemented breaking changes and will update the documentation to reflect your changes as well, added a new DSL macro.

**Comment by grkek** [comment]
@yanecc Added the documentation, check it out.

**Comment by yanecc** [comment]
> @yanecc Added the documentation, check it out.

Looks good. 👍

**Pull request merged**
